### ISSUE TITLE
JPEG support

### ISSUE THREAD

**Issue by alessandrofrancesconi** [redwarp/9-Patch-Resizer#16]
Great tool! Will it be possible to work with JPEG images too?
Right now, if I put a .JPG image as input, the generated scaled versions are all PNG

**Comment by Wavesonics** [comment]
getting jpg support out would ROCK

**Comment by redwarp** [comment]
Sorry about that ! I've been working on it and then forgot about it on the way... I'll be absent next week, but I'll finish and release it the week after, I promise.

**Comment by redwarp** [comment]
It's getting there! If you pull the last source, and build it, it will work. Do you have any comments/suggestions ?
I'll bundle a new version at some point this week-end otherwise

**Comment by redwarp** [comment]
Here goes : https://github.com/redwarp/9-Patch-Resizer/releases/tag/1.4.0
