### ISSUE TITLE
mipmap option

### ISSUE THREAD

**Issue by cdraeger** [redwarp/9-Patch-Resizer#17]
Hi, I was just reading through Lollipop/Nexus 6 docs and best-practice posts and saw that for the Nexus 6 (launcher-) icon, `mipmap`\- instead of `drawable`-folders are suggested:

http://android-developers.blogspot.de/2014/10/getting-your-apps-ready-for-nexus-6-and.html
http://stackoverflow.com/questions/23935810/mipmap-drawables-for-icons

I guess a simple checkbox/switch would do the trick. What do you think? I could probably fork and do this myself if I find some time, I just wanted to pin it here first.

**Comment by NSouth** [comment]
Hey, I love this tool! But I want to join my voice with the others and say that a mipmap option would be great. I think exporting into "mipmap-" or "drawable-" folders would be great. Just my two cents. Thanks for saving me time!

**Comment by djonko** [comment]
https://github.com/djonko/9-Patch-Resizer  i  changed generate "drawable-_" folder to "mipmap-_"  folder

**Comment by SjoerdvGestel** [comment]
@djonko any way to get a compiled .exe from your fork?

**Comment by redwarp** [comment]
@djonko you really don't need an exe you know? .exe are just wrapper around the jar. But the jar itself is executable :-)

**Comment by redwarp** [comment]
Lost in the sands of time
