### ISSUE TITLE
blurry image

### ISSUE THREAD

**Issue by wbersaty** [redwarp/9-Patch-Resizer#18]
some output images blured.Some images Volume become bigger.

**Comment by redwarp** [comment]
I'm working on a "sharpen" feature currently. It will be optional, because wether it makes the results better or not is subjective.

**Comment by noam2** [comment]
all images are blurry, is anything you can do?

**Comment by redwarp** [comment]
@noam2 Please provide some sample images.

**Comment by noam2** [comment]
can you give me your email and ill show you

**Comment by redwarp** [comment]
@noam2 Same username, at gmail

**Comment by noam2** [comment]
redwarp@gmail.com ? sent you , you didnt reply

**Comment by redwarp** [comment]
@noam2 Sorry, went of grid for the weekend.
I looked at your image and... the original is a 94x116 mdpi image. And from that, you generate the other densities (hdpi, xhdpi, xxhdpi). Which makes your image bigger, and of course blurry.

For this tool to work for you, you need to have an original in xxhdpi. And it will create for you smaller pictures. If you create bigger pictures, like in photoshop, you get a blurred result.

Cheers

**Comment by noam2** [comment]
hey there ... thanks for replying, really appreciate it
the thing is - in your program, there is an option to put the original
image in any density (ldpi, hdpi, xhdpi ..etc), so i thought it would work
(maybe you should change it so people don't get confused).

so basically youre saying to supply the original image in xxhdpi - OK.

I have a question, if you could give me a tip please, how do i know what
size to make the original xxhdpi picture, for it to look good and fit all
other screens ? and if i have an animation of 100 drawables, (that i
programmed with AnumationDrawable) - do i need to resize every pic, with
your program ? and if yes in what size ?

Thanks in advance , youre help is important and appreciated

**Comment by redwarp** [comment]
@noam2 "mdpi" should be the base of what you want as the smallest image. So if you want the mdpi image to be 100x100 pixel, you would create a high quality 300x300 xxhdpi image. (Remember that mdpi is x1, hdpi is x1.5, xhdpi is x2 and xxhdpi is x3)

I don't think that you need to care for ldpi anymore. Recent phones have usually a better screen density than that.

I would not advice to do a 100 images animation: it would probably use up too much memory.

**Comment by noam2** [comment]
ok , thanks again.

A few things :
i've seen everywhere that ldpi is still used, so r u sure not to include it
?

Regarding the animation -  it works ... but i'll try to reduce number of
frames anyway , but you still didn't answer my question - suppose i'll have
50 or 20 or 10 frames , will i have to take care of every picture ?

And last - about the density calculation , how did you get to that ratio
and is it absolute ? from now on should i do that calculation (x1, x1.5,
x2, x3) ?

THANK YOU

**Comment by redwarp** [comment]
@noam2 About densities, depends what kind of phones you target, and in what market I guess. In western countries, I think they are no useless, not sure about India or China.

For animation: yes, you would take care of every pictures

As for the densities calculation, that's basic android stuff :-) check https://developer.android.com/guide/practices/screens_support.html and read the part about "Alternative drawables"

I hope it helps!

**Comment by noam2** [comment]
again, i really thank you for your'e help :)
you said that most likely the densities are useless - so what do you
recommend , to supply only one size for all pics ? and if so for what
folder ? (ldpi,hdpi etc...)

and thanks i read the link with the focus you gave.

Just want to know how should i deploy my app with all the pics in it. What
folders , how to include all drawables and all of that, cause its my first
app

**Comment by redwarp** [comment]
Hey sorry, I don't think I can really provide more help than that. I would personally use mdpi, hdpi, xhdpi and xxhdpi. I'm not sure it's still appropriate though, maybe you should look for stats about screen density usage?

All the resources and where to put them are explained in the Android Developer tutorials (https://www.udacity.com/course/android-developer-nanodegree-by-google--nd801) it's free.

This is outside of the problem of this ticket, so I will comment on that no further.

Good luck with your app.
