### ISSUE TITLE
Jpeg quality setting

### ISSUE THREAD

**Issue by Wavesonics** [redwarp/9-Patch-Resizer#20]
First, thank you so much for the work on jpeg support!

To make this tool even more flexible and fit all needs, having the jpeg output quality configurable would be ideal.

Maybe just a settings dialog to enter what output quality you want for your jpegs.

Another thought is that most jpegs actually store the quality setting they were exported with in their metadata, we could read that and use that for the output quality. Not sure if that's a good idea, but thought it'd mention it. (Even with this, you'd probably still want an option to override it with some configurable value)

**Comment by redwarp** [comment]
Yeah, I have to write on a settings panel I think.

**Comment by redwarp** [comment]
I'll look into the "get meta data for export" thingy ^_^
