### ISSUE TITLE
Drop doesn't work anymore

### ISSUE THREAD

**Issue by ninette111** [redwarp/9-Patch-Resizer#25]
I used this tool several times in the last year and it worked perfectly! Today I faced the problem, that droping files onto the window doesn't work anymore. What could be the problem?
Is there another way to include the files?

**Comment by redwarp** [comment]
Hi there, well, not currently, I should probably change it so that if I click on the arrow, I open a file picker dialog... Meanwhile, you can use it with command line I guess, but it's not practical for everyone
The fact that "dropping" files doesn't work is troubling. What OS are you using it with?

**Comment by ninette111** [comment]
Win8 since one month. Before I had Windows7 where it worked fine. Maybe that the reason?

**Comment by redwarp** [comment]
Hum, don't know, I have Win8 at home and it works properly. Could you try rebooting? Or it might be a problem with your java version? Do you use the .exe file or the .jar? (You can try both, they are both doing exactly the same. The .exe is actually just a wrapper around the .jar)

**Comment by ninette111** [comment]
ok, I'll try it, thanks...

**Comment by redwarp** [comment]
But okay, I'm adding it to my "todo" list: add a file picker, when the user click on the bit arrow icon in the window

**Comment by ninette111** [comment]
Good idea :) Thanks

**Comment by redwarp** [comment]
https://github.com/redwarp/9-Patch-Resizer/releases/tag/1.4.2 A new release with a file picker, tell me what you think!

**Comment by ninette111** [comment]
oh great! thank you so much for this quick new release! :)
