### ISSUE TITLE
command line processing

### ISSUE THREAD

**Issue by sebastien-tiscar** [redwarp/9-Patch-Resizer#26]
Nice tool I use a lot (when i finally figure out what density i gave the assets in ;))
Looking the Main class, it looks like the command line only takes a list of files.
It should be possible to specify the input density and the output densities wanted, as it happens by using the UI.

Otherwise a bit of documentation about how to use it using the command line (or maybe i didn't find it)
Tx

**Comment by redwarp** [comment]
No you are right, there is not much documentation ^_^
Currently, the command line will use the same densities.json file as the UI version. Meaning if you save your settings, command line will do that. Which is not really good, I agree. It should be possible to take, as input, a specified json file, or as you say, input and output densities.

**Comment by sebastien-tiscar** [comment]
ok, I think I figured out by reading the source code, and the answer you just gave me. It looks like you use the densities.json file and use the "source" field as the default desity...wish is enough for me, i just have to copy/paste the jar + json in my project, write a gradle command....et voilà c est tout bon ! :)
Thanks

**Comment by redwarp** [comment]
Way to go ;-) félicitations

**Comment by redwarp** [comment]
Lost in the sands of time
