### ISSUE TITLE
Add 'mipmap' option for output!!!

### ISSUE THREAD

**Issue by aligorji** [redwarp/9-Patch-Resizer#27]
Right now create 'drawable' folders for each densities, It seems that 'mipmap' also need to be for launcher icon for android.

**Comment by EzraLopez** [comment]
If you are willing to dive into the source code to accomplish this, I think you can start here: https://github.com/redwarp/9-Patch-Resizer/blob/4cf91e25f2631da672dbc28800ba1e471e25ece9/src/net/redwarp/tool/resizer/worker/ImageScaler.java#L98

**Comment by redwarp** [comment]
@EzraLopez My problem is more that I haven't come up with a good UI to solve this issue.

**Comment by EzraLopez** [comment]
@redwarp why don't just change it to mipmap? That's the way Android Studio does it.

**Comment by redwarp** [comment]
@EzraLopez Because then it does not generate in the drawable folder anymore. It would be one or the other. So I need to put a ui element somewhere to choose I guess.

**Comment by EzraLopez** [comment]
@redwarp well, if you really want to keep the drawable option and the UI is the only issue I'd say keep it simple. For example, you can do it below "Output density:" as "Output folder:" and using a drop down list like with "Input density:".

**Comment by aligorji** [comment]
I have a suggestion. use editable drop down list then put `drawable` and `mipmap` for default items value and user can select them, also user can enter custom value then save in setting file for next time usage.

**Comment by Kolyall** [comment]
@redwarp can you support and solve the issue? just add a checkbox to switch between drawable and mipmap folder

**Comment by redwarp** [comment]
@Kolyall frankly, this project is not really in active development right now, and I don't have that much time lately to look at it. But you are more than welcome to participate in the code base, and then I'll package a new .exe
Otherwise, I'm afraid I can't give you a fixed date.

**Comment by redwarp** [comment]
Duplicate #17
