### ISSUE TITLE
Work with Java 1.9?

### ISSUE THREAD

**Issue by imperialstormtrooper** [redwarp/9-Patch-Resizer#31]
Love this tool. Installed it on a new laptop and it is saying "This application requires a Java Runtime Environment 1.6.0". I have 1.9 (JRE and JDK) installed on the laptop and in the path. To complicate things a bit I am having to point to the Android Studio JRE for my JAVA_HOME. Either way I believe the JRE is greater than 1.6. Probably something stupid on my side...thoughts?

**Comment by imperialstormtrooper** [comment]
So I installed Java 1.8 JRE and added it to my path and the tool is now working. So it is incompatible with Java 1.9 JRE. Heaven knows what Oracle has done now... :)

**Comment by redwarp** [comment]
Thanks for trying this!
