### ISSUE TITLE
Help for building a project

### ISSUE THREAD

**Issue by andrecool-68** [redwarp/9-Patch-Resizer#33]
Please add help how to compile this project and in which program to do it.

**Comment by redwarp** [comment]
Last time I check, it was a maven project! So you can assemble and all with maven.
But I will try to convert that to gradle.

**Comment by andrecool-68** [comment]
@redwarp Can Visual Studio compile such projects?

**Comment by redwarp** [comment]
I'm not sure, I never tried. It will definitely work with IntelliJ

**Comment by andrecool-68** [comment]
@redwarp I have used NetBeans, the project came together without any problems!
IntelliJ IDEA has not tested yet, maybe another time.
Thanks for help!

**Comment by redwarp** [comment]
Anytime! I really have to dust this old project off :-)
