### ISSUE TITLE
Command line option : use-nearest-neighbor

### ISSUE THREAD

**Issue by humpity** [redwarp/9-Patch-Resizer#35]
I would like to use this program from a command-line (no-gui).
But I tried icons that don't need interpolation or anti-aliasing during resizing,
and they do suffer a bit compared to using 'nearest-neighbor'.
So I would like to request a nearest-neighbor resize filter option on the command line.

**Comment by redwarp** [comment]
Hey!

Do you have an exemple of an icon that would not need interpolation?
But anyway, I'm currently not really maintaining this tool, as I tend to not really use it anymore. (I am now using vector drawables as often as possible instead, and for sure do not really use 9-patch anymore)
So I probably will not have the bandwidth to work on that?
But feel free to fork the tool and implement it, and then we can see about merging your suggestion!

**Comment by redwarp** [comment]
Closing this as it never got updated.
